version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5201

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5201:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=football.db
      - FOOTBALL_API_KEY=${FOOTBALL_API_KEY}
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: